---
title: "Chapter 1b, Data Visualization"
format: gfm
---
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point()

ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = species)
) +
  geom_point()
  
  ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g, color = species)
) +
  geom_point() +
  geom_smooth(method = "lm")
  
  ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(mapping = aes(color = species)) +
  geom_smooth(method = "lm")
  
  ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(mapping = aes(color = species, shape = species)) +
  geom_smooth(method = "lm")
  
  ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
  geom_point(aes(color = species, shape = species)) +
  geom_smooth(method = "lm") +
  labs(
    title = "Body mass and flipper length",
    subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
    x = "Flipper length (mm)", y = "Body mass (g)",
    color = "Species", shape = "Species"
  ) +
  scale_color_colorblind()

# Exercise Pt.1/3 
# question 3
 ggplot(
  data = penguins,
  mapping = aes(x = bill_length_mm, y = bill_depth_mm)
) +
  geom_point(mapping = aes(color = species, shape = species)) +
  geom_smooth(method = "lm")
 
# question 5
  ggplot(data = penguins) 
  + 
  geom_point()
  
# question 6 & 7 
  ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
) +
geom_point(na.rm = TRUE) +
ggtitle("Scatterplot with na.rm = TRUE (NA values removed) ") +
  labs(
    caption = "Data come from the palmerpenguins package"
)

# question 8 
ggplot(
  data = penguins,
  mapping = aes(x = flipper_length_mm, y = body_mass_g)
  )+
  geom_point(aes(color = bill_depth_mm)) +
  geom_smooth()

# Visualizing Distributions
ggplot(penguins, aes(x = species)) +
  geom_bar()

# Frequencies in Bar Graphs
ggplot(penguins, aes(x = fct_infreq(species))) +
  geom_bar()

# Histogram binwidth
ggplot(penguins, aes(x = body_mass_g)) +
  geom_histogram(binwidth = 20)
ggplot(penguins, aes(x = body_mass_g)) +
  geom_histogram(binwidth = 2000)

# Density Plot
ggplot(penguins, aes(x = body_mass_g)) +
  geom_density()

# Exercise Pt.2/3
# question 1
ggplot(penguins, aes(y=species)
)+
geom_bar()

# question 2
ggplot(penguins, aes(x = species)) +
  geom_bar(color = "red")
ggplot(penguins, aes(x = species)) +
  geom_bar(fill = "red")
#fill = red makes bars fully red, color = red only outlines bars

# question 4
ggplot(diamonds, aes(x = carat)) +
geom_histogram(bins = 30)
ggplot(diamonds, aes(x = carat)) +
geom_histogram(bins = 1000)

# Visualizing Relationships
ggplot(penguins, aes(x = species, y = body_mass_g)) +
  geom_boxplot()

# Two Categorical Variables
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar()
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")

# Three or More Variables
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species, shape = island))
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species, shape = species)) +
  facet_wrap(~island)

# Exercises pt3/3
# question 2
ggplot(mpg, aes(y = hwy, x = displ),) +
geom_point(color = "blue", shape = "triangle")

# question 3
ggplot(mpg, aes(y = hwy, x = displ),?mpg
) +
geom_point(color = "blue", shape = "triangle") +
geom_line(aes(color = fl))

# question 5
ggplot(penguins, aes(y = bill_depth_mm, x = bill_length_mm)) +
geom_point(aes(color = species)) +
facet_wrap(~species)

# question 6
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point() +
  labs(color = "species")

# question 7
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "fill")

# Saving Your Plots
ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) + 
geom_point()
ggsave(filename = "penguin-plot.png")